# This file generates the GitHub Actions matrix
---
include:
  - board: nice_nano_v2
    shield: sofle_left
  - board: nice_nano_v2
    shield: sofle_right
  - board: nice_nano_v2
    shield: settings_reset
